
logging:
  level:
    org.hibernate.SQL: DEBUG
spring:
  datasource:
    url: jdbc:h2:./h2/default;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create
  quartz:
    job-store-type: jdbc
    properties:
      org.quartz:
        jobStore:
          clusterCheckinInterval: 20_000
          isClustered: true
    jdbc:
      initialize-schema: never
  sql:
    init:
      mode: always
server:
  servlet:
    context-path: "/api"
